import type { SkinModel } from "../../hooks/useSkin";

export interface PresetSkin {
  id: string;
  nickname: string;
  nameRu: string;
  nameEn: string;
  model: SkinModel;
  url: string;
  avatarUrl: string;
  tag: string;
  descriptionRu: string;
}

export interface PresetCape {
  id: string;
  nameRu: string;
  nameEn: string;
  url: string;
  previewColor: string;
  tag: string;
  descriptionRu: string;
}

export const PRESET_SKINS: PresetSkin[] = [
  {
    id: "notch",
    nickname: "Notch",
    nameRu: "Нотч (Создатель)",
    nameEn: "Notch",
    model: "classic",
    url: "https://minotar.net/skin/Notch",
    avatarUrl: "https://minotar.net/avatar/Notch/64",
    tag: "Легенда",
    descriptionRu: "Легендарный скин создателя Minecraft",
  },
  {
    id: "dream",
    nickname: "Dream",
    nameRu: "Dream",
    nameEn: "Dream",
    model: "classic",
    url: "https://minotar.net/skin/Dream",
    avatarUrl: "https://minotar.net/avatar/Dream/64",
    tag: "Ютубер",
    descriptionRu: "Знаменитый зеленый силуэт с белой улыбкой",
  },
  {
    id: "technoblade",
    nickname: "Technoblade",
    nameRu: "Technoblade",
    nameEn: "Technoblade",
    model: "classic",
    url: "https://minotar.net/skin/Technoblade",
    avatarUrl: "https://minotar.net/avatar/Technoblade/64",
    tag: "Легенда",
    descriptionRu: "Свиной король в королевской мантии и золотой короне",
  },
  {
    id: "steve",
    nickname: "MHF_Steve",
    nameRu: "Классический Стив",
    nameEn: "Classic Steve",
    model: "classic",
    url: "https://minotar.net/skin/MHF_Steve",
    avatarUrl: "https://minotar.net/avatar/MHF_Steve/64",
    tag: "Классика",
    descriptionRu: "Оригинальный каноничный стив с широкими плечами",
  },
  {
    id: "alex",
    nickname: "MHF_Alex",
    nameRu: "Алекс (Slim)",
    nameEn: "Slim Alex",
    model: "slim",
    url: "https://minotar.net/skin/MHF_Alex",
    avatarUrl: "https://minotar.net/avatar/MHF_Alex/64",
    tag: "Классика",
    descriptionRu: "Изящная модель Slim с тонкими руками 3px",
  },
  {
    id: "herobrine",
    nickname: "MHF_Herobrine",
    nameRu: "Херобрин",
    nameEn: "Herobrine",
    model: "classic",
    url: "https://minotar.net/skin/MHF_Herobrine",
    avatarUrl: "https://minotar.net/avatar/MHF_Herobrine/64",
    tag: "Миф",
    descriptionRu: "Таинственный шахтер с ледяными белыми глазами",
  },
  {
    id: "dantdm",
    nickname: "DanTDM",
    nameRu: "DanTDM",
    nameEn: "DanTDM",
    model: "classic",
    url: "https://minotar.net/skin/DanTDM",
    avatarUrl: "https://minotar.net/avatar/DanTDM/64",
    tag: "Ютубер",
    descriptionRu: "Культовый образ профессора лаборатории",
  },
  {
    id: "grian",
    nickname: "Grian",
    nameRu: "Grian",
    nameEn: "Grian",
    model: "classic",
    url: "https://minotar.net/skin/Grian",
    avatarUrl: "https://minotar.net/avatar/Grian/64",
    tag: "Hermitcraft",
    descriptionRu: "Красная толстовка знаменитого мастера построек",
  },
  {
    id: "mumbo",
    nickname: "MumboJumbo",
    nameRu: "Mumbo Jumbo",
    nameEn: "Mumbo Jumbo",
    model: "classic",
    url: "https://minotar.net/skin/MumboJumbo",
    avatarUrl: "https://minotar.net/avatar/MumboJumbo/64",
    tag: "Hermitcraft",
    descriptionRu: "Джентльмен в смокинге с густыми усами",
  },
  {
    id: "tommyinnit",
    nickname: "TommyInnit",
    nameRu: "TommyInnit",
    nameEn: "TommyInnit",
    model: "classic",
    url: "https://minotar.net/skin/TommyInnit",
    avatarUrl: "https://minotar.net/avatar/TommyInnit/64",
    tag: "Ютубер",
    descriptionRu: "Красно-белая футболка популярного британского стримера",
  },
  {
    id: "skeppy",
    nickname: "Skeppy",
    nameRu: "Skeppy",
    nameEn: "Skeppy",
    model: "classic",
    url: "https://minotar.net/skin/Skeppy",
    avatarUrl: "https://minotar.net/avatar/Skeppy/64",
    tag: "Ютубер",
    descriptionRu: "Алмазный персонаж в голубой толстовке",
  },
  {
    id: "sparklez",
    nickname: "CaptainSparklez",
    nameRu: "CaptainSparklez",
    nameEn: "CaptainSparklez",
    model: "classic",
    url: "https://minotar.net/skin/CaptainSparklez",
    avatarUrl: "https://minotar.net/avatar/CaptainSparklez/64",
    tag: "Легенда",
    descriptionRu: "Автор Fallen Kingdom и Revenge в фирменной майке",
  },
];

export const PRESET_CAPES: PresetCape[] = [
  {
    id: "migrator",
    nameRu: "Migrator Cape",
    nameEn: "Migrator Cape",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAaElEQVR4nO3QoRGAMAAEwTRBBQiKpREao47gwbMiJ868+tlxbsdcuaEP6ALQB3QBvIf72j/pkwEEEEAAAQTwE8BqBaAP6ALQB3QB6AO6APQBXQD6gC4AfUAXgD6gC0Af0AWgD+iWB3gARM1QrtpJ+xoAAAAASUVORK5CYII=",
    previewColor: "#8b1527",
    tag: "Microsoft",
    descriptionRu: "Официальный плащ за миграцию аккаунта на Microsoft",
  },
  {
    id: "anniversary15",
    nameRu: "15th Anniversary",
    nameEn: "15th Anniversary Cape",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAdUlEQVR4nO3WoQ2AQBQFQQwtUAaF0CaFgibhkEwCK1ace5lvblr27fhzkx6gC0AP0F0A5nUZpocGEMALAHcQeuDrAH+6fgABDACe3l+rj5AeoAtAD9AFoAfoAtADdAHoAboA9ABdAHqALgA9QBeAHqALQA/QnQky8xjHMYftAAAAAElFTkSuQmCC",
    previewColor: "#16a34a",
    tag: "Microsoft",
    descriptionRu: "Юбилейный изумрудно-зеленый плащ крипера к 15-летию Minecraft",
  },
  {
    id: "vanilla",
    nameRu: "Vanilla Cape",
    nameEn: "Vanilla Cape",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAbUlEQVR4nO3SoQ2AQBQFwVOUQSE0QxnUSjUQLAmWEbdi1Zn3JzfWbb9mbugBugC+Hs5j4eMCEADP4e/0yH5AAAEEEEAAAfwLMEsB6AG6APQAXQB6gC4APUAXgD6gC0AP0AWgB+gC0AN0AegBuhs2K7l2Qy5RsAAAAABJRU5ErkJggg==",
    previewColor: "#1e3a5f",
    tag: "Microsoft",
    descriptionRu: "Награда владельцам Java и Bedrock версий Minecraft",
  },
  {
    id: "cherry_blossom",
    nameRu: "Cherry Blossom",
    nameEn: "Cherry Blossom Cape",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAdklEQVR4nO3SsQmAUBTFUMdwHzdyBXdyMnvFVhDLA/4UqV6TG950rPs5MpMW0BRAC2gK8HbY5oXLkQD38CdaknzAKPQBb4e/D/8MMAoF0AKaAmgBTQG0gKYAWkBTAC2gKYAW0BRAC2gKoAU0BdACmgJoAc3wAS7AUsqBe11m8wAAAABJRU5ErkJggg==",
    previewColor: "#f472b6",
    tag: "Microsoft",
    descriptionRu: "Розовый плащ цветущей вишни по итогам голосования",
  },
  {
    id: "twitch",
    nameRu: "Twitch Cape",
    nameEn: "Twitch Cape",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAV0lEQVR4nO3SQQoAEBRF0b8nS7VLm2AuY6846paMXifV25g/V+kB6QCkB6QDsD+cTnokgATAfn81PwAAgPwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAALjVAn4wnvWQAdEwAAAAAElFTkSuQmCC",
    previewColor: "#9333ea",
    tag: "Microsoft",
    descriptionRu: "Пурпурный юбилейный плащ партнерства с платформой Twitch",
  },
  {
    id: "tiktok",
    nameRu: "TikTok Cape",
    nameEn: "TikTok Cape",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAaklEQVR4nO3SIRKAMBAEwdgU//8oDwAqAomlRUaM3+u6Medx79zQA3QB6AG6T4BxXnxcAAEEEMDvAOvwNz2uD5AAuxSAHqALQA/QBaAH6ALQA3QB6AG6APQAXQB6gC4APUAXgD6gC0AP0D0eM/DkjDubMAAAAABJRU5ErkJggg==",
    previewColor: "#09090b",
    tag: "Microsoft",
    descriptionRu: "Черный плащ с неоновой нотой коллаборации TikTok",
  },
  {
    id: "mojang",
    nameRu: "Mojang Studios",
    nameEn: "Mojang Studios Cape",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAATElEQVR4nO3VsQkAIAwAQWdwHmd3NW0sFdKISO4gXZp8k9JrG7em/EAAAQQQQIA1J7vjIruvbwsRQAABBBDAGxRAAAEESBoAAACAhCYk3tnAsOuXVgAAAABJRU5ErkJggg==",
    previewColor: "#be123c",
    tag: "Mojang",
    descriptionRu: "Официальный плащ сотрудников и разработчиков студии Mojang",
  },
  {
    id: "mcc_prismarine",
    nameRu: "MCC 15th Cape",
    nameEn: "MCC 15th Cape",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAf0lEQVR4nO2XsQ2AMBADs0BGYU8GYB+WYB+oIxcpT+JcnJTSPvmLjHmdr5lBB6AJAcdzb99/YhFgK78IMJaPBRhF9ATM5WMBRhE9AXP5WIBRRE/AXD4WYBTR3yAdgKYC6AA0FUAHoKkAOgBNBdABaCqADkBTAXQAmgqgA9DoBXw0WFgBzlTRCQAAAABJRU5ErkJggg==",
    previewColor: "#0d9488",
    tag: "Microsoft",
    descriptionRu: "Призмариновый плащ коллаборации с турниром Minecraft Championship",
  },
  {
    id: "minecon2011",
    nameRu: "Minecon 2011",
    nameEn: "Minecon 2011",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAUElEQVR4nO3VsQkAIAwAQccI6P47OJ12VhZpRMQ7SGeRfGPprY1TU14ggAACrIUj6nZ2x2Xe3r4tRQABBBBAAN+gAAIIIIAAAnwZAAAAgA9NZHDzj5IJgp8AAAAASUVORK5CYII=",
    previewColor: "#b91c1c",
    tag: "Minecon",
    descriptionRu: "Первый исторический плащ фестиваля Minecon 2011",
  },
  {
    id: "minecon2012",
    nameRu: "Minecon 2012",
    nameEn: "Minecon 2012",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAYElEQVR4nO3SMQqAMBBFwZR2lt7B63srLxEhYBd0U4RFnIHtUvgflnXb66wrX9D78PNY2kVGPr3N3hYigAACCPD7APeItxt9m70txB8ggAACCCCAAAIIMOGytwEAAEDfBSnKiHH7bQ/WAAAAAElFTkSuQmCC",
    previewColor: "#eab308",
    tag: "Minecon",
    descriptionRu: "Официальный плащ Minecon 2012 с золотой киркой",
  },
  {
    id: "minecon2013",
    nameRu: "Minecon 2013",
    nameEn: "Minecon 2013",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAV0lEQVR4nO3QsQ3AIBAEQSohpwbadAdugu4gJrFJ0AsxI11GwG/KpfZdSycQQAABpk8/b5v2deDf2+jblggggAACCCCAAAIIsGHRty0RQIDLAwAAAHChAeKM4M3pB4RmAAAAAElFTkSuQmCC",
    previewColor: "#64748b",
    tag: "Minecon",
    descriptionRu: "Официальный плащ Minecon 2013 с редстоун-поршнем",
  },
  {
    id: "minecon2015",
    nameRu: "Minecon 2015",
    nameEn: "Minecon 2015",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAU0lEQVR4nO3VoQ3AIBRFUSbpIIzImCgkG4AF02JIQzgneQ7zryE8MbVdCycQQAABBBiXS532duDX279vWyKAAAIIIIBvUAABBBBAgDsDAAAAcKEOSExijDEDZtUAAAAASUVORK5CYII=",
    previewColor: "#1e3a8a",
    tag: "Minecon",
    descriptionRu: "Синий плащ Minecon 2015 с железным големом",
  },
  {
    id: "minecon2016",
    nameRu: "Minecon 2016",
    nameEn: "Minecon 2016",
    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAAUUlEQVR4nO3WsQ0AEBRFURso7WAfO9pQSaVTaETEOcnrNP9WQky5n1p4gQACCCDAXC1tudVxO29v37ZFAAEEEEAAAQTwERJAAAH+DAAAAMCHBoEiu2FmKpW5AAAAAElFTkSuQmCC",
    previewColor: "#7e22ce",
    tag: "Minecon",
    descriptionRu: "Фиолетовый плащ Minecon 2016 с глазами Странника Края",
  },
];
