// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FindMinecraftVersion(arg1:string):Promise<main.Version>;

export function Greet(arg1:string):Promise<string>;
